---
- name: Set up nginx on both web servers
  hosts: all
  tasks:
    - name: Install nginx on both hosts
      community.general.apk:
        name: nginx
        state: present
        update_cache: true
      tags:
        - install_nginx
      become: true

    - name: Start & enable nginx
      ansible.builtin.service:
        name: nginx
        state: started
      become: true

    - name: Copy the nginx config file and restart nginx
      ansible.builtin.copy:
        src: files/static_site.cfg
        dest: /root/static_site.cfg
        owner: nginx
        group: nginx
        mode: '0644'
      become: true

    - name: Create symlink
      ansible.builtin.file:
        src: /root/static_site.cfg
        dest: /etc/nginx/http.d/web.conf
        owner: nginx
        group: nginx
        state: link
      become: true

    - name: Copy the content of the web site
      ansible.builtin.copy:
        src: files/static-site-src/
        dest: /home/angelo/static-site
        mode: '0644'

    - name: Restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
      become: true

- name: Set up install_haproxy on web1 only
  hosts: web1
  tasks:
    - name: Install haproxy on web1 server
      ansible.builtin.apk:
        name: haproxy
        state: present
        update_cache: true
      tags:
        - install_haproxy
      become: true
    - name: Start & enable haproxy
      ansible.builtin.service:
        name: haproxy
        state: started
      become: true
