---
- name: Set up nginx on both web servers
  hosts: all
  tasks:
    - name: Install nginx on both hosts
      community.general.apk:
        name: nginx
        state: present
        update_cache: true
      tags:
        - install_nginx
      become: true

    - name: Create the www directory inside /var
      ansible.builtin.file:
        path: /var/www
        state: directory
        owner: nginx
        group: nginx
        mode: 0775
      become: true

    - name: Remove the original default.conf
      ansible.builtin.file:
        path: /etc/nginx/http.d/default.conf
        state: absent
      become: true

    - name: Copy the nginx config file and restart nginx
      ansible.builtin.copy:
        src: templates/default.conf
        dest: /etc/nginx/http.d/default.conf
        owner: nginx
        group: nginx
        mode: 0644
      become: true

    - name: Copy the content of the web site
      ansible.builtin.copy:
        src: files/static-site-src/
        dest: /var/www/static-site
        owner: nginx
        group: nginx
        mode: 0644
      become: true

    - name: Extend the static web site with some local information
      ansible.builtin.script: files/welcome.sh
      become: true

    - name: Start/Restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
      become: true

- name: Set up haproxy on web1 only
  hosts: web1
  tasks:
    - name: Install haproxy on web1 server
      community.general.apk:
        name: haproxy
        state: present
        update_cache: true
      tags:
        - install_haproxy
      become: true

    - name: Remove the original haproxy.cfg
      ansible.builtin.file:
        path: /etc/haproxy/haproxy.cfg
        state: absent
      become: true

    - name: Copy the round robin configuration
      ansible.builtin.copy:
        src: templates/haproxy.cfg
        dest: /etc/haproxy/haproxy.cfg
        mode: 0644
      become: true

    - name: Start/Restart haproxy
      ansible.builtin.service:
        name: haproxy
        state: restarted
      become: true
