---
- name: Remove nginx from both servers
  hosts: all
  tasks:
    - name: Stop nginx
      ansible.builtin.service:
        name: nginx
        state: stopped

    - name: Ensure nginx is not installed
      community.general.apk:
        name: nginx
        state: absent

    - name: Recursively remove nginx directory in /etc
      ansible.builtin.file:
        path: /etc/nginx
        state: absent

    - name: Recursively remove nginx directory in /var/lib
      ansible.builtin.file:
        path: /var/lib/nginx
        state: absent

- name: Remove haproxy from web1
  hosts: web1
  tasks:
    - name: Stop haproxy
      ansible.builtin.service:
        name: haproxy
        state: stopped

    - name: Ensure haproxy is not installed
      community.general.apk:
        name: haproxy
        state: absent

    - name: Recursively remove haproxy directory in /etc
      ansible.builtin.file:
        path: /etc/haproxy
        state: absent
